name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  configuration: Release
  productNamespacePrefix: "ReactiveMarbles"

jobs:
  build:
    runs-on: windows-2022
    outputs:
      nbgv: ${{ steps.nbgv.outputs.SemVer2 }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0
        lfs: true

    - name: Install .NET
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: |
            6.0.x
            7.0.x
            8.0.x

    - name: NBGV
      id: nbgv
      uses: dotnet/nbgv@master
      with:
        setAllVars: true

    - name: NuGet Restore
      run: dotnet restore
      working-directory: src
      
    - name: Build
      run: dotnet build --configuration=${{ env.configuration }} --verbosity=minimal --no-restore
      working-directory: src

    - name: Run Unit Tests and Generate Coverage
      uses: glennawatson/coverlet-msbuild@v2
      with:
        project-files: '**/*Tests*.csproj'
        no-build: true
        exclude-filter: '[${{env.productNamespacePrefix}}.*.Tests.*]*'
        include-filter: '[${{env.productNamespacePrefix}}*]*'
        output-format: cobertura
        output: '../../artifacts/'
        configuration: ${{ env.configuration }}

    - name: Pack
      run: dotnet pack --configuration=${{ env.configuration }} --verbosity=minimal --no-restore
      working-directory: src

    - name: Upload Code Coverage
      shell: bash
      run: |
        echo $PWD
        bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy -t ${{ env.CODECOV_TOKEN }} -s '$PWD/artifacts' -f '*.xml'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Create NuGet Artifacts
      uses: actions/upload-artifact@master
      with:
        name: nuget
        path: '**/*.nupkg'
